<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<?php require_once 'shared/header.php';?>
  <title>Profile not found</title>

</head>
<body>
 <div class="container">
  <?php include_once 'shared/go-back.php';?>
  <div class="row">
    <div class="col s12 m6 offset-m3">

      <div class=" card-panel">
        <h4><b>
          <i class="fa fa-user fa-fw"></i>Profile not found</b></h4>
        </div>

      </div>
    </div>
  </div>
  <?php require_once 'shared/scripts.php';?>
</body>
</html>	