<?php
/**
* Created by Sublime Text.
* User: Eze <eebarcoch@gmail.com>
* Date: 
*/
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<?php require_once 'shared/header.php';?>
  <title>Error</title>
 
</head>
<body>
 <div class="container">
    <?php include_once 'shared/go-back.php';?>
  <div class="row">
    <div class="col s12 m6 offset-m3">

      <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class=" card-panel">
               <h4><b><?=$data?></b></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <?php require_once 'shared/scripts.php';?>
</body>
</html>	