<?php
/**
* Created by Sublime Text.
* User: Eze <eebarcoch@gmail.com>
* Date: 
*/
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<?php require_once '../app/header.php';?>
  <title>Error</title>
 
</head>
<body>
 <div class="container">
  <div class="row">
  <div class="col s12 m8">
    <div class="left">
     <a href="/api/facebook/profiles" class="btn btn-large waves-effect waves-light"><i class="material-icons">keyboard_backspace</i></a>
    </div>
      </div>
  </div>
  <div class="row">
    <div class="col s12 m6 offset-m3">

      <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class=" card-panel">
               <h4><b><?=$data?></b></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <?php require_once '../app/scripts.php';?>
</body>
</html>	