<!DOCTYPE html>
<html lang="en">
<head>
	<?php require_once 'shared/header.php';?>
  <title>User facebook profile</title>
</head>
<body>
  <div class="container">
   <?php include_once 'shared/go-back.php';?>
   <div class="row">

    <div class="col s12 m8">

     <div class="card small">
      <div class="card-image waves-effect waves-block waves-light">
        <img src="<?= $profile['cover']['source']?>" class=" responsive-img activator" title="User cover">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
         <img src="<?= $profile->getPicture()->getUrl()?>" title="User picture" class="circle responsive-img">
         <?= $profile->getName()?>


         <i class="material-icons right">more_vert</i>


       </span>

       <p> <a target="_blank" href="https://facebook.com/<?=$profile->getId()?>">Go to facebook full profile</a></p>
     </div>
     <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><?= $profile->getName()?><i class="material-icons right">close</i></span>

      <ul>
        <?php foreach($profile as $key => $field):?>
          <?php if(isset($key)):?>

            <li>
              <b><?=$key?>:</b>
              <?php switch ($key) {
                case 'gender':
                if($field == 'male'){
                  echo '<i class="fa fa-male"></i>';
                }elseif($field=="female"){
                  echo '
                  <i class="fa fa-female"></i>';
                }
                break;
                case 'cover':
                 echo '<a href="'.$field["source"].'" target="_blank">Show</a>';
                break;
                case 'picture':
                echo '<a href="'.$field["url"].'" target="_blank">Show</a>';
                break;
                case 'id':
                case 'name':
                case 'email':

                echo '<span>'.$field.'</span>';
                break;
                case 'devices':
                echo '<span>'.$field[0]["os"].'</span>';

                break;
                case 'age_range':
                if($field["min"])
                echo '<span>'."+".$field["min"].'</span>';
                break;

              }
              ?>
            </li>
          <?php endif;?>
        <?php endforeach;?>
      </ul>
    </div>
  </div>


</div>
<div class="col s12 m4">
 <ul class="collection with-header">
   <li class="collection-header"><h4>Retrieved fields</h4></li>



   <?php foreach($profile as $key => $field):?>
    <?php if(isset($key)):?>
     <li class="collection-item"><div><?=$key?><a href="#!" class="secondary-content"><i class="material-icons">check</i></a></div></li>
   <?php endif;?>
 <?php endforeach;?>
</ul>
</div>
</div>

</div>
<?php require_once 'shared/scripts.php';?>
</body>
</html>	