<?php
/**
* Created by Sublime Text.
* User: Eze <eebarcoch@gmail.com>
* Date: 
*/
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<?php require_once '../app/header.php';?>
  <title>Search for a facebook user profile</title>
 
</head>
<body>
 <div class="container">
  <div class="row">
    <div class="col s12 m6 offset-m3">

      <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class=" card-panel">

              <form method="post" action="/api/facebook/profiles">
                <input  placeholder="'me' or user id here" name="id">

                <button type="submit" class=" waves-effect waves-light btn">
                  Go!</button>     

                </form>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <?php require_once '../app/scripts.php';?>
</body>
</html>	